/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author chmov
 */
public class Schedule extends javax.swing.JFrame {

    /**
     * Creates new form Schedule
     */
    public Schedule() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HourField = new javax.swing.JTextField();
        OtherInfoTextField = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        OtherInfoLabel = new javax.swing.JLabel();
        BookButton = new javax.swing.JToggleButton();
        HourLabel = new javax.swing.JLabel();
        DateField = new javax.swing.JTextField();
        ValueField = new javax.swing.JTextField();
        DateLabel = new javax.swing.JLabel();
        ValueLabel = new javax.swing.JLabel();
        ServiceCombo = new javax.swing.JComboBox<>();
        ServiceLabel = new javax.swing.JLabel();
        ClientLabel = new javax.swing.JLabel();
        ClientCombo = new javax.swing.JComboBox<>();
        IdLabel = new javax.swing.JLabel();
        Schedule = new javax.swing.JLabel();
        IdField = new javax.swing.JTextField();
        Panel = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(HourField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 80, 20));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        OtherInfoTextField.setViewportView(jTextArea1);

        getContentPane().add(OtherInfoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 210, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Client", "Service", "Value($)", "Date", "Hour", "Other Info"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 260, 460, 190));

        OtherInfoLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OtherInfoLabel.setText("Other Info");
        getContentPane().add(OtherInfoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        BookButton.setBackground(new java.awt.Color(182, 136, 17));
        BookButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BookButton.setForeground(new java.awt.Color(204, 204, 204));
        BookButton.setText("Book");
        getContentPane().add(BookButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 150, -1));

        HourLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HourLabel.setText("Hour");
        getContentPane().add(HourLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));
        getContentPane().add(DateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 80, 20));
        getContentPane().add(ValueField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 80, 20));

        DateLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DateLabel.setText("Date");
        getContentPane().add(DateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        ValueLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ValueLabel.setText("Value($)");
        getContentPane().add(ValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        ServiceCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hair", "Beard", "Hair + Beard" }));
        getContentPane().add(ServiceCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 80, -1));

        ServiceLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ServiceLabel.setText("Service");
        getContentPane().add(ServiceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        ClientLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ClientLabel.setText("Client");
        getContentPane().add(ClientLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        ClientCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Josh", "Paul", "Lenny" }));
        getContentPane().add(ClientCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 80, -1));

        IdLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IdLabel.setText("Id");
        getContentPane().add(IdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        Schedule.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Schedule.setText("Schedule");
        getContentPane().add(Schedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));
        getContentPane().add(IdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 80, 20));

        Panel.setIcon(new javax.swing.ImageIcon("C:\\Netbeans Projects\\BarberShop\\src\\main\\java\\View\\Images\\Painel.png")); // NOI18N
        getContentPane().add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 240));

        Background.setIcon(new javax.swing.ImageIcon("C:\\Netbeans Projects\\BarberShop\\src\\main\\java\\View\\Images\\Schedule.png")); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -120, 570, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Schedule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JToggleButton BookButton;
    private javax.swing.JComboBox<String> ClientCombo;
    private javax.swing.JLabel ClientLabel;
    private javax.swing.JTextField DateField;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JTextField HourField;
    private javax.swing.JLabel HourLabel;
    private javax.swing.JTextField IdField;
    private javax.swing.JLabel IdLabel;
    private javax.swing.JLabel OtherInfoLabel;
    private javax.swing.JScrollPane OtherInfoTextField;
    private javax.swing.JLabel Panel;
    private javax.swing.JLabel Schedule;
    private javax.swing.JComboBox<String> ServiceCombo;
    private javax.swing.JLabel ServiceLabel;
    private javax.swing.JTextField ValueField;
    private javax.swing.JLabel ValueLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
